# -*- coding: utf-8 -*-
"""Data Cleaning and preprocessing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XquG1E6QOLrkwkwTP_BQMAn4kF1BiMHq
"""

import pandas as pd
import numpy as np

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', np.nan],  # Name column with missing value
    'Age': [25, np.nan, 30, 35, 40],  # Age column with missing value
    'Gender': ['Female', 'Male', np.nan, 'Male', 'Female'],  # Gender column with missing value
    'Salary': [50000, 60000, np.nan, 80000, 90000],  # Salary column with missing value
    'Category': ['A', 'B', 'A', 'B', 'C']  # Categorical variable
}

df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

df['Age'].fillna(df['Age'].median(), inplace=True)  # Replace missing age with median
df['Salary'].fillna(df['Salary'].mean(), inplace=True)  # Replace missing salary with mean
df['Gender'].fillna(df['Gender'].mode()[0], inplace=True)  # Replace missing gender with mode
df.dropna(inplace=True)  # Drop remaining missing values

df_encoded = pd.get_dummies(df, columns=['Category'], drop_first=True)

print("\nCleaned DataFrame:")
print(df_encoded)